# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: dotnet sdk
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '2.x'
# - task: SonarCloudPrepare@1
#   displayName: sonar prepare analysis
#   inputs:
#     SonarCloud: 'sonarcloud-escalonn'
#     organization: '2102-feb08-net'
#     scannerMode: 'MSBuild'
#     projectKey: '2102-feb08-net_trainer-code'
#     projectName: 'EmailApp'
#     extraProperties: 'sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/*/coverage.opencover.xml'



- script: dotnet build ./StoreApp/StoreApp.WebUI --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test ./StoreApp/StoreApp.Tests --configuration $(buildConfiguration)
  displayName: ' dotnet test for valid first name'